# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: cross-clipboard

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: "non-linux"
    skip: false
    env:
      - CGO_ENABLED=1
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: "linux"
    skip: false
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Check https://goreleaser.com/customization/homebrew/
brews:
  - homepage: 'https://github.com/ntsd/cross-clipboard'
    description: 'A multi device clipboard sharing over P2P network.'
    directory: Formula
    commit_author:
      name: ntsd
      email: jo06942@gmail.com
    repository:
      owner: ntsd
      name: homebrew-cross-clipboard
